[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags = -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
upload_port = rfc2217://192.168.100.90:4002
monitor_port = rfc2217://192.168.100.90:4002
lib_deps =
    ESP32Async/AsyncTCP @ ^3.4.10
    ESP32Async/ESPAsyncWebServer @ ^3.7.3
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.0
    ayushsharma82/ElegantOTA @ ^3.1.5
